# Generated by Django 2.2.2 on 2019-06-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_auto_20190613_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
