# Generated by Django 2.2.2 on 2019-06-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_auto_20190614_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
    ]
